services:
  mongodb-init:
    build: ./db
    depends_on:
      - biblio-api-mongo0
      - biblio-api-mongo1
      - biblio-api-mongo2
    logging:
      driver: none

  biblio-api-mongo0:
    hostname: biblio-api-mongo0
    container_name: biblio-api-mongo0
    image: mongo:8.0.13
    ports:
      - 27017:27017
    expose:
      - 27017
    restart: unless-stopped
    entrypoint: ["/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs0"]
    environment:
      - MONGO_INITDB_DATABASE=RD
    volumes:
      - ./volume-database:/data/db

  biblio-api-mongo1:
    hostname: biblio-api-mongo1
    container_name: biblio-api-mongo1
    image: mongo:8.0.13
    ports:
      - 27018:27017
    expose:
      - 27018
    restart: unless-stopped
    entrypoint: ["/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs0"]
    attach: false

  biblio-api-mongo2:
    hostname: biblio-api-mongo2
    container_name: biblio-api-mongo2
    image: mongo:8.0.13
    ports:
      - 27019:27017
    expose:
      - 27019
    restart: unless-stopped
    entrypoint: ["/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs0"]
    attach: false

  mongo-express:
    image: mongo-express:1.0.2
    container_name: biblio-api-mongo-express
    restart: always
    ports:
      - 8082:8081
    environment:
      - ME_CONFIG_MONGODB_SERVER=biblio-api-mongo0
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_MONGODB_ADMINUSERNAME=
      - ME_CONFIG_MONGODB_ADMINPASSWORD=
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=admin
      - ME_CONFIG_MONGODB_URL=mongodb://biblio-api-mongo0:27017,biblio-api-mongo1:27017,biblio-api-mongo2:27017/?replicaSet=rs0
    depends_on:
      - biblio-api-mongo0
      - biblio-api-mongo1
      - biblio-api-mongo2
    attach: false
